services:
  downloader:
    build: downloader
    environment:
      - RPCPORT=6800
      - RPCSECRET=TEST123
      - TORSERVNUM=50
    volumes:
      - ./downloader/conf:/conf
      - ./downloader/log:/log
      - ./downloader/run:/run
      - ./downloader/data:/data
        # network_mode: host
    ports:
      - 127.0.0.1:6800:6800

  controller:
    build: controller
    # network_mode: host
    volumes:
      - ./controller/conf:/conf
      - ./controller/logs:/logs
      - ./controller/www:/var/www
    ports:
      - 127.0.0.1:8080:8080

